<?php
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
$session=$objectManager->get(\Magento\Customer\Model\Session::class);

if ($session->getCustomer()->getId()) {
?>
    <p style="color:green;">Enter integer Points to redeem reward</p>
    <form id="redeem-reward" method="POST" action="/redeem/Redeem/index">
        <span class="int-error" id="int-error" style="display: none;">Please input integer only</span>
        <input type="text" placeholder="Points" name="redeem-reward-points" id="int-points" />
    </form>
    <button type="button" class="redeem-reward">
        <span>Apply Redeem Points</span>
    </button>

    <script type="text/javascript">
        require([
            'jquery'
        ], function($) {
            $(document).on('click', '.redeem-reward', function() {
                var inputString = $("#int-points").val();
                if (isNaN(inputString / 1))
                    $("#int-error").css({
                        "display": "block",
                        "color": "red"
                    });
                else {
                    $("#int-error").css({
                        "display": "none"
                    });
                    $('#redeem-reward').submit();
                }
            })
        });
    </script>
<?php
}
?>